### ISSUE TITLE
Pip installer broken. Cannot install from Github Repository.

### ISSUE THREAD

**Issue by FFX01** [anpylar/anpylar#1]
I tried installing using Pip. The install works fine, but I get an error when trying to use the CLI to create a new application as in this step of the tutorial: https://docs.anpylar.com/tutorial/top0/index.htmlista.html

This is the error message:

```
[Errno 2] No such file or directory: '/home/justin/projects/python/client/venv/lib/python3.5/site-packages/anpylar/data/anpylar_d.auto_vfs.js'
```

I took a look in the directory as specified in the error message above. Sure enough, that file was missing. The script does generate most of the files it's supposed to except for `anpylar.js` and `package.json`.

This same error occurs regardless of which of the following tags I set: `--htmlista`, `--selectista`, `--pythonista`.

Thinking that the version of the package on Pip may be out of date, I attempted to install from this repository and received this error message:

```
Collecting git+https://github.com/anpylar/anpylar.git
  Cloning https://github.com/anpylar/anpylar.git to /tmp/pip-7079r887-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/justin/projects/python/client/venv/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-7079r887-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-7079r887-build/
```

Here are my system specs:

```
                          ./+o+-       justin@Taisho
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.4.0-83-generic
           .++ .:/++++++/-.+sss/`      Uptime: 1h 32m
         .:++o:  /++++++++/:--:/-      Packages: 3129
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.48
       .:+o:+o/.          `+sssoo+/    Resolution: 3120x1600
  .++/+:+oo+o:`             /sssooo.   DE: Unity 7.4.0
 /+++//+:`oo+o               /::--:.   WM: Compiz
 \+/+o+++`o++o               ++////.   WM Theme: Ambiance
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Ambiance [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: ubuntu-mono-dark
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i5-6600K CPU @ 3.9GHz
           .o:`.syhhhhhhh/.oo++o`      GPU: GeForce GTX 960
               /osyyyyyyo++ooo+++/     RAM: 2457MiB / 15980MiB
                   ````` +oo+++o\:    
                          `oo++.  
```

I am using Python 3.5.

**Comment by anpylar** [comment]
> This is the error message:
> ```
> [Errno 2] No such file or directory: '/home/justin/projects/python/client/venv/lib/python3.5/site-packages/anpylar/data/anpylar_d.auto_vfs.js'
> ```

It's a packaging error. The generation of the wheel package didn't pull in some of the needed files. To be corrected in a few minutes

> 
> Thinking that the version of the package on Pip may be out of date, I attempted to install from this repository and received this error message:
> 
> ```
> Collecting git+https://github.com/anpylar/anpylar.git
>   Cloning https://github.com/anpylar/anpylar.git to /tmp/pip-7079r887-build
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/home/justin/projects/python/client/venv/lib/python3.5/tokenize.py", line 454, in open
>         buffer = _builtin_open(filename, 'rb')
>     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-7079r887-build/setup.py'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-7079r887-build/
> ```

That's because the repository holding the *cli* is `anyplar-cli`. It's explained in the `README` of the front page.

**Comment by anpylar** [comment]
See: https://github.com/anpylar/anpylar-cli/issues/1
