### ISSUE TITLE
browser console show an 404 error at home page

### ISSUE THREAD

**Issue by robertpro** [anpylar/anpylar#5]
Hi, I have run this command:

```bash
# Create the project
anpylar-application myapp

# Go into the directory
cd myapp

# Start the development web server
anpylar-serve .
```

And in the localhost:2222/

I can see this error in the console: `Error 404 means that Python module app was not found at url http://localhost:2222/app.py`

I am not sure if this file should be created with `anpylar-application` command, or I should create myself

**Comment by backtrader** [comment]
You have created an empty application which does nothing.

> I can see this error in the console: Error 404 means that Python module app was not found at url http://localhost:2222/app.py

The standard Python mechanism as implemented by *brighton* tries to locate the `app` package in several locations (just CPython does on-disk). The reports you see in the console are simply those that didn't succeed. When the application is packaged there are no such messages.

You need to add content to the generated `myapp` application. Please read the tutorial:

  - https://docs.anpylar.com/tutorial/index.html

**Comment by anpylar** [comment]
You have created an empty application which does nothing.

> I can see this error in the console: Error 404 means that Python module app was not found at url http://localhost:2222/app.py

The standard Python mechanism as implemented by *brighton* tries to locate the `app` package in several locations (just CPython does on-disk). The reports you see in the console are simply those that didn't succeed. When the application is packaged there are no such messages.

You need to add content to the generated `myapp` application. Please read the tutorial:

  - https://docs.anpylar.com/tutorial/index.html
