### ISSUE TITLE
Session management? URL authentication and authorization?

### ISSUE THREAD

**Issue by metaperl** [anpylar/anpylar#7]
Hello, I did not see a section in the [docs](https://docs.anpylar.com/index.html) that discussed things essential to production-quality web development. The main issue being user authentication and authorization for actions.

Do you have any examples of requiring a user login before accessing the main app?

**Comment by anpylar** [comment]
User authentication on the client-side is documented in the advanced sample:

  - https://docs.anpylar.com/tutorial/tourer/index.html

And an example of server side authentication in an integration with `Flask` is here:

  - https://github.com/anpylar/flaskpylar
